### PR TITLE
feat(lanelet2_extensions): add query curbstones from vector map

### PR DESCRIPTION
**Pull request by saka1-s**
## Description

This PR makes enable to query curbstones from vector map.
The purpose of this feature is to publish curbstones as MarkerArray.

The background of this PR is below.
If the vector map contains a curbstone, we would like to check the position of the curbstone on rviz.
Because we need to know how much clearance do we have. 
I propose adding a marker array of curbstone.
https://github.com/autowarefoundation/autoware.universe/pull/4958
Screenshot from 2023-09-11 19-29-01

## Tests performed

PSim

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by saka1-s** [comment]
@mitsudome-r Could you please review this PR?

**Review by mitsudome-r — APPROVED** [review]
LGTM.

@saka1-s The code looks okay, but could you write in description why you want to add this function so that we can track the reason in the future?

**Comment by mitsudome-r** [comment]
@saka1-s Also, DCO check is failing. Could you sign-off your commit? https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/commit-guidelines/#commit-rules

**Comment by saka1-s** [comment]
@mitsudome-r 
Thank your review and I appreciate your help.
I update the background of PR in the description.
I also signed-off my commit and pushed again.

**Pull request merged**
