### PR TITLE
ci: split reverse-reference workflow

### PR DESCRIPTION
**Pull request by kenji-miyake**
It's enough if we can run the `reverse-reference` workflow on `workflow_dispatch` events.
So I'll split it.

### CODE REVIEW

**Review by KeisukeShima — APPROVED** [review]

**Comment by kenji-miyake** [comment]
Ah, perhaps I should change the title or branch? @KeisukeShima What do you think about it?

**Comment by KeisukeShima** [comment]
@kenji-miyake In my opinion, you added `sync-files-reverse-reference`.
So, how about `ci(sync-files-reverse-reference): add reverse-reference workflow` as a title?

**Comment by kenji-miyake** [comment]
@KeisukeShima Oh, I'm sorry. I was talking about the title that will be created by this workflow such as #26.

Regarding the title of this PR, I use these rules now:
- If the workflow is newly added, don't add the scope.
- If the workflow already exists, add the scope.

**Comment by KeisukeShima** [comment]
Ah, I see. The current title is easy to understand. I think it would be better if you put the sync source at the end.
In this case, the title would look like `chore: sync files from autoware.universe`.

**Comment by kenji-miyake** [comment]
Okay, I'll add it.

**Comment by kenji-miyake** [comment]
But I think sometimes we pull from other repositories, so I'll write `chore: sync files of reverse references` instead of `from autoware.universe`.

**Review by KeisukeShima — APPROVED** [review]
@kenji-miyake I was thinking of changing the `autoware.universe` part by referring to the repository tag in yaml file.
But I think your change is also easy to understand. So I approved it.

**Comment by kenji-miyake** [comment]
> I was thinking of changing the autoware.universe part by referring to the repository tag in yaml file.

What does this mean? :thinking:

**Comment by KeisukeShima** [comment]
> > I was thinking of changing the autoware.universe part by referring to the repository tag in yaml file.
> 
> What does this mean? thinking

For example,
- sync-files-reverse-reference.yaml
```
- repository: autowarefoundation/REPO_NAME
...
```
The title looks like:
`chore: sync files from REPO_NAME`

**Comment by kenji-miyake** [comment]
Ah, I see. In that case, we should split YAML files.
Okay, let's consider which is better when we have to sync from other repositories in the future. :+1:

**Pull request merged**
