### PR TITLE
build: add runtime dependencies

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by esteve** [comment]
@jspricke thanks, but `ros_environment` does not export any build artifacts that are used by downstream packages, so it's still incorrect to use it in this context.

**Comment by esteve** [comment]
On second thought, this have the potential of working, but something tells me it's not entirely correct.

**Comment by jspricke** [comment]
It is working, see my build here: https://github.com/jspricke/autoware_packages/actions/runs/3986179280/jobs/6834443358

**Comment by jspricke** [comment]
Next problem is here, btw.: https://github.com/esteve/autoware.universe/pull/1

**Comment by jspricke** [comment]
Now against the correct upstream: https://github.com/autowarefoundation/autoware.universe/pull/2721

**Review by esteve — APPROVED** [review]
This is more correct than #142 , thanks @jspricke for your contribution

**Pull request merged**
