### PR TITLE
feat: add autoware_lint_common

### PR DESCRIPTION
**Pull request by 1222-takeshi**
# Related Issue
#1

# Description
Add autoware_lint_common for formatting.

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@1222-takeshi Thank you! Could you squash all commits and make the DCO check pass? :pray:

**Comment by 1222-takeshi** [comment]
@kenji-miyake DCO check passed. :+1:

**Comment by kenji-miyake** [comment]
@1222-takeshi Do you want to merge this before I'll add CI later or can you wait for that?
In other words, do you want to refer this in `build_depends.repos` of autoware.universe now?

**Comment by 1222-takeshi** [comment]
The timing of the merge can be anytime, so I wait for the CI to be merged. :bow:

**Comment by kenji-miyake** [comment]
Will merge after #3 is resolved.

**Review by kenji-miyake — APPROVED** [review]

**Comment by taikitanaka3** [comment]
@kenji-miyake 
can you merge this?
this PR is necessary to build autoware_launch package

**Comment by kenji-miyake** [comment]
I'll merge this after setting up the CI tomorrow!

**Comment by kenji-miyake** [comment]
pre-commit.ci run

**Pull request merged**
